### ISSUE TITLE
[BUG] Rofi not able to parse .rasi file

### ISSUE THREAD

**Issue by Vantazz** [Crylia/crylia-theme#11]
**Describe the bug**
When running rofi -show drun -theme ~/.config/rofi/rofi.rasi
and rofi -show drun -theme ~/.config/rofi/window.rasi I encounter the same issue where rofi is not able to parse the config file correctly
Specifically lines with @ to another variable such as border-color:                       @accent;
don't seem to work, and instead tells me "The following errors were detected when starting rofi: failed to resolve variable 'border' in: 'window { border-color: var(border);}'" in a large white box that covers the entire image.

**Expected behavior**
Rofi runs with correct theme applied

**Information (please complete the following information):**
 - Arch
 - awesome v4.3-1360-gc539e0e43
"The following errors were detected when starting rofi: failed to resolve variable 'border' in: 'window { border-color: var(border);}'"

**Comment by Crylia** [comment]
Can you please provide the output of `rofi -v`?

**Comment by Vantazz** [comment]
Version: 1.7.3-61-gc0feb2eb (makepkg) Sorry I should have included this in the original post

**Comment by Crylia** [comment]
window { border-color: var(border);}
That should be in line 24 ish, does it work once you removed the line?

**Comment by Vantazz** [comment]
In what file sorry? I looked in rofi.rasi and could not find it

**Comment by Crylia** [comment]
24:	border-color:					@border;

Its in this repo, rofi.rasi is correct but it is also in window.rasi.

Its in the folder rofi, not any of the other folder

**Comment by Vantazz** [comment]
Ah yes that fixed it

**Comment by Crylia** [comment]
Perfect, I will update both files and remove the other junk that I forgot to remove. Thanks for letting me know!
