### ISSUE TITLE
[BUG] AwesomeWM crash on startup

### ISSUE THREAD

**Issue by Xalose** [Crylia/crylia-theme#14]
Just a note I am a complete noob and this is my first time working with any WM so I know nothing and treat me as such :)

**Describe the bug**
When logging in with AwesomeWM on my Fedora 35 (linux-surface) I get the following error:
error: /home/NAME/.config/awesome/src/core/notifications.lua/:29: attempt to call a nil value (field 'connect_signal')

**To Reproduce**
1. Select 'awesome' when logging in
2. Enter password and log in

**Expected behavior**
Honestly no idea I probably made a really dumb mistake

**Screenshots**
Sorry no screenshots

**Information (please complete the following information):**
 - Fedora 35 on linux-surface kernel
 - Idk the version of awesome? How do I check

**Comment by Crylia** [comment]
This sounds like you haven't installed the git version but rather the one that comes with your package manager.
You can check your awesome version with "awesome -v".
You can also find a guide on the README.md on how to install awesome-git or on the awesomewm github itself.

**Comment by Crylia** [comment]
Closing this since you didn't answer in a week now. If the issue still persists feel free to reopen the issue with more information.
