### ISSUE TITLE
[QUESTION] Not Really, Just A Complement

### ISSUE THREAD

**Issue by Thomashighbaugh** [Crylia/crylia-theme#16]
If you frequent r/unixporn, you may or may not have seen me giving the mods hell and since I use the same avi, I am just emerging myself from a deep exploration of awesomewm, which I could probably write a book on honestly, thus have seen and maintain a comprehensive list of configurations that use more than a single `rc.lua` or modular configurations and am somewhat tired of a certain psuedo-skeudomorphic appearance in vogue on that sub and why if this was posted there, why I missed it as I am somewhat over the same thing redundantly you get with its mod's questionable choices for what is worthy of the sidebar.  

## Clearly You Have the Most Interesting Config of 2022

Clearly the most original and well written (like me, you also use comments which alone puts you into your own league) which I find highly impressive and love the attention to detail and use of your own unique elements like the titlebar buttons, etc. I am not the most easy person to impress in terms of awesome, as I like originality, the reason that awesome even acquired its reputation in the `ricing` scene. You show that with this work and I look forward to seeing this evolve in the future. 

Thomas Leon Highbaugh

**Comment by Crylia** [comment]
Thank you very much, I always intended to make a rice that is readable and can be extended without any hassle. I'd say that I'm lacking a lot of comments in the main code for widgets etc but I plan to improve on that for my upcoming 2.0 release.

Cheers
