### ISSUE TITLE
[BUG] Application bar stays hidden if all open windows are minimized

### ISSUE THREAD

**Issue by CardboardCarl** [Crylia/crylia-theme#17]
**Information (please complete the following information):**
 - Arch Linux x64 5.17.9-arch-1
 - Awesome v4.3-1360-gc539e0e43 
 - Compiled against Lua 5.4.4 (running with 0.9.2)
 - No error message (How???)

**To Reproduce**
1. Open any two applications
2. If you minimize one and not the other, the application bar still works
3. If you minimize both, the Application bar stays hidden

**Expected behavior**
I was under the impression the bar should only hide itself if applications are open, but reappear without hovering over it when everything is minimized.

**Additional context**
I don't expect you to fix this, Kievits, I'm just putting it here in case I got something wrong before I start debugging it myself. :)

**Comment by Crylia** [comment]
It seems like I forgot to update the dock when a client gets minimized.

**Comment by CardboardCarl** [comment]
Thanks for the fix!
