### ISSUE TITLE
Swapping escape and caps is very confusing

### ISSUE THREAD

**Issue by Shardj** [Crylia/crylia-theme#21]
https://github.com/Crylia/crylia-theme/blob/cc008323426574b4278e28fa3eba56f408931852/awesome/src/theme/user_variables.lua#L41

Can we get a warning for this in the README, or can unexpected keybinds be moved to an optionally included file? Now that I've found this line it's not a problem for me but this should help others who can't figure out why their caps are stuck on.

Maybe this is just me being stupid because I'm using AwesomeWM for the first time

**Comment by Crylia** [comment]
Oh damn I totally forgot that was still there. I'm gonna remove it and probably make a more universal default config later.
