### ISSUE TITLE
[ENHANCEMENT] Init script

### ISSUE THREAD

**Issue by JulianGR** [Crylia/crylia-theme#26]
Hello,

I've been trying to install the theme and everything seems to work just fine, but not without a couple of days testing. There were missing steps in the installation of awesome, rofi and picom. I have created a script that automates everything, just in case someone wants to quickly get the theme working without all the hassle that I went through. Here it is:

Tested in latest version of Pop_os! as of June 8th 2022. Perhaps you could add it in the repo as an "autoinstall.sh" script or sth. 

```
#!/usr/bin/bash

# dependencies for meson, ninja, rofi, awesome and all extra optional packages
sudo apt -y install meson ninja-build cmake cmake-data pkg-config papirus-icon-theme xorg build-essential git vim make autoconf automake pkg-config flex bison check go-md2man doxygen cppcheck ohcount pulseaudio-utils upower bluez xorg xfce4-power-manager playerctl lightdm light-locker

# fonts
cd
wget https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf 
wget https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf
wget https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf
wget https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf

# awesome-git (awesome from apt does NOT work)
cd
sudo apt  build-dep -y awesome
git clone https://github.com/awesomewm/awesome
cd awesome
make package
cd build/
sudo dpkg -i awesome*.deb

# rofi (rofi  from apt does NOT work)
cd
git clone https://github.com/davatorium/rofi/
meson setup build
sudo ninja -C build install

# picom  (picom from apt does NOT work)
cd
git clone https://github.com/jonaburg/picom
cd picom
meson --buildtype=release . build
sudo ninja -C build install

cd
git clone https://github.com/Crylia/crylia-theme
cd crylia-theme
cp -r awesome ~/.config/.
cp -r picom.conf ~/.config/.
cp -r rofi ~/.config/.
cp -r alacritty ~/.config/.

```

**Comment by Crylia** [comment]
Hello thanks for trying to improve the installation, could you please do a PR and I will then comment things further?
It would also be nice to add an config for Archlinux since I think that Archlinux is a bit more popular under ricers.

Also one note for now, the next update will include submodules, so please change the git command to --recurse-submodules.

**Comment by JulianGR** [comment]
yeah sure, im on it =)
