### ISSUE TITLE
[BUG] Awesomewm doesnt startup

### ISSUE THREAD

**Issue by Cephetir** [Crylia/crylia-theme#28]
**Describe the bug**
On awesomewm login shows error: /home/cephetir/.config/awesome/src/core/notifications.lua/:29: attempt to call a nil value (field 'connect_signal') and nothing works (buttons, terminal, etc)

**To Reproduce**
1. Log in to awesome
2. See error

**Expected behavior**
Well I'm not sure but awesomewm startup obviously

**Screenshots**
![image](https://user-images.githubusercontent.com/62209929/172816971-fd7bfc4f-2498-4877-8181-2329e3086c64.png)

**Information (please complete the following information):**
 - Linux Mint
 - awesome v4.3 (Too long) 

**Additional context**
Just installed clean fork of crylia theme

**Comment by Crylia** [comment]
You need to install the git version and not the stable of awesome.
https://github.com/awesomeWM/awesome#installing-current-git-master-as-a-package-receipts

**Comment by Crylia** [comment]
Can you start awesome manually from a different tty with startx /path/to/awesome ?

**Comment by Cephetir** [comment]
> Can you start awesome manually from a different tty with startx /path/to/awesome ?

How to do it? I'm not rly into this kind of stuff.
**startx awesome** returns /usr/lib/xorg/Xorg.wrap: Only console users are allowed to run the X server

**Comment by Cephetir** [comment]
Also I found this in logs
<sub>error while running function!
stack traceback:
	/usr/local/share/awesome/lib/awful/_compat.lua:37: in main chunk
	[C]: in function 'require'
	/usr/local/share/awesome/lib/awful/init.lua:9: in main chunk
	[C]: in function 'require'
	/usr/local/etc/xdg/awesome/rc.lua:8: in main chunk
error: /usr/local/share/awesome/lib/awful/_compat.lua:37: attempt to call a nil value (field 'set_newindex_miss_handler')
2022-06-09 15:32:25 E: awesome: main:866: couldn't find any rc file</sub>

**Comment by Crylia** [comment]
`couldn't find any rc file`
Are you sure you have my theme files at .config/ ?

> How to do it?
switch tty with ctrl + alt+ F1 or F2 etc until it drops you into a terminal. Then you type startx /usr/bin/awesome this is usually where awesome is located at

**Comment by Cephetir** [comment]
> `couldn't find any rc file` Are you sure you have my theme files at .config/ ?

yes, I tested everything already and nothing works

**Comment by Crylia** [comment]
try to install awmtt https://github.com/serialoverflow/awmtt and see if you can start it there from something like gnome

**Comment by Cephetir** [comment]
> try to install awmtt https://github.com/serialoverflow/awmtt and see if you can start it there from something like gnome

Doesn't work, same error 😕

**Comment by Crylia** [comment]
There is a PR with an install script, it has some errors but maybe you get more luck with it?

**Comment by Crylia** [comment]
@Cephetir Can you try to install script that I just pushed?

**Comment by Crylia** [comment]
Since you didn't answer in a week I'm gonna close it for now, its the issue still persists please feel free to reopen this issue.
