### ISSUE TITLE
[QUESTION] Hey, can I use the normal Picom instead?

### ISSUE THREAD

**Issue by floweringnights** [Crylia/crylia-theme#29]
Question in title, and if I cannot use the normal version due to configuration issues, how can I configure it so that it'll work with the theme?

**Comment by Crylia** [comment]
You can use it but there will be some features missing from the fork I'm using. Picom is independent from my config so you can use your own picom.conf instead and except for picom still everything will still be the same.

**Comment by floweringnights** [comment]
> You can use it but there will be some features missing from the fork I'm using. Picom is independent from my config so you can use your own picom.conf instead and except for picom still everything will still be the same.

alright, then! How can I change the position of the window titlebar, by the way? I'm more used to it being on the top instead of to the left of the application window

**Comment by Crylia** [comment]
> 

This will be a bit more work since the layout is made for a left sided titlebar. You will need to rewrite the layout in titlebar.lua

**Comment by floweringnights** [comment]
Hey, what about the icon theme? Can I just use any other icon theme instead of Papirus?

**Comment by Crylia** [comment]
> Hey, what about the icon theme? Can I just use any other icon theme instead of Papirus?

Theoretically yes, but not ATM. I finished a new xdg-icon-lookup according to the freedesktop standard but I haven't pushed it into the dev branch yet.

**Comment by Crylia** [comment]
I'm going to close this now. If there are any further questions feel free to reopen this issue.
