### ISSUE TITLE
[QUESTION] polybar colors

### ISSUE THREAD

**Issue by changsijay** [Crylia/crylia-theme#31]
seems some colors are missing

```
error: Invalid value for "module/date.label-foreground", using default value (reason: The reference ${colors.green} does not exist (no fallback set))
error: Invalid value for "module/cpu.label-foreground", using default value (reason: The reference ${colors.bluegreen} does not exist (no fallback set))
```

also I am trying polybar tho it looks not same as screenshot here

![image](https://user-images.githubusercontent.com/245306/179348431-44e5093d-8229-4157-b11a-acb91f9473ae.png)

**Comment by changsijay** [comment]
also rofi powermenu related files are missing

```
"rofi -show power-menu -modi power-menu:~/.config/rofi/rofi-power-menu -theme ~/.config/rofi/powermenu/powermenu.rasi"
```

**Comment by Crylia** [comment]
Well I haven't touched polybar or i3 in almost a year now, so I expect things to be wrong by now. I might take a look after I finish my vacation.

**Comment by changsijay** [comment]
no hurry, curious what combination are you using now?
after trying some polybar and rofi and tiled wm, 
I am thinking keep using gnome42 for simplicity XD

**Comment by Crylia** [comment]
I will probably remove the i3 and polybar config since this is primarily my awesome repo and I don't use them anyways. Rofi will also be completely removed next release so It would break those anyways.
