### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by yyy33** [Crylia/crylia-theme#32]
Nice theme, please ask why my layout is so compact
![2022-08-04_15-16](https://user-images.githubusercontent.com/51548147/182848980-c5382465-b636-416c-be32-3a1a03bdd165.png)

**Comment by Crylia** [comment]
Your resolution is super small, you can either decrease your DPI to make everything smaller, or remove some widgets so it fits

**Comment by yyy33** [comment]
> Your resolution is super small, you can either decrease your DPI to make everything smaller, or remove some widgets so it fits

Thank you, good job
