### ISSUE TITLE
Used install script - awesome doesn't change from base setup on arch [BUG]

### ISSUE THREAD

**Issue by ramandelbaum** [Crylia/crylia-theme#33]
I installed all the dependencies and ensured they were on my system.
I used your arch_install.sh and let the script move everything / double check everything was installed
I verified the required config folders were moved to the right directories.
However when I switch into awesome, it gives me the original layout / design of awesome without an ability to open terminal or right click on screen to quit awesome.
Running on up to date Arch Linux

**Comment by Crylia** [comment]
Is the rc.lua at `$HOME/.config/awesome/rc.lua`?

Also do you have a screenshot? Because you should be able to at least launch the default xterm terminal with the default theme.

**Comment by ramandelbaum** [comment]
I do, and it’s not working.
It might be a conflict of interest with something in my config folder
regarding another window manager since it’s actually not showing the
default awesome setup.
I will try a fresh install in a virtual machine running arch to see
if works as planned.
If it does I’ll close out the bug because it was an error on my end

**Comment by ramandelbaum** [comment]
Did a fresh install and re-used your script.
Everything is working properly now besides very laggy input when typing / browsing firefox.
That's more a xorg /driver issue I'll have to fix and not your fault - I've fixed it in the past regarding awesome and my native cpu graphics. 
Closing because fixed!
