### ISSUE TITLE
Different DPI / Font size for bar [QUESTION]

### ISSUE THREAD

**Issue by ramandelbaum** [Crylia/crylia-theme#34]
How would I go about changing the size of the font / wording for the top right bar?
I see it pulls from .Xresources to resize it - however due to my native resolution being 3072 x 1980 I sort of need to remain at a dpi of 192 to make general use tolerable.
if it's not easily fixable I can live with it for now until I trouble shoot
![dpi issue](https://user-images.githubusercontent.com/105895699/192637301-3f21b8a3-4dfb-4c62-b6c0-5385ea81c108.png)

my previous bug and this issue aside - I love the setup!
I've been wanting to get away from a full DE to a window manager setup and all things considered this is great

**Comment by ramandelbaum** [comment]
Fixed: was able to make easily readable by changing the forced_height function in right_bar.lua

**Comment by Crylia** [comment]
Yeah I changed that up in the dev branch, I didn't use dpi() for the values I think
