### ISSUE TITLE
[QUESTION] Can you make the rofi client switcher close and exit when you release the mod key

### ISSUE THREAD

**Issue by bend-n** [Crylia/crylia-theme#35]
<key>alt</key> + <key>tab</key>: switches selection to next window initially
release <key>alt</key>: switch to that window

**Comment by Crylia** [comment]
You can simply change the key from alt to mod

**Comment by bend-n** [comment]
No I mean close the window switcher when you release the mod key, currently, you have to press enter after selecting the window.

**Comment by Crylia** [comment]
I think that may be a rofi problem. Anyways I wouldn't really want to work on it since I ditched rofi all together in my dev branch that will get merged at some point

**Comment by bend-n** [comment]
In the dev branch, is this behaviour implemented?

**Comment by Crylia** [comment]
Yes, but there is no easy way of installing that branch atm, there are many hard dependencies and some unmerged PR's from awesome that are currently needed. Tbh even I have problems getting it running on another system because I've taken things to the next level
