### ISSUE TITLE
The  central window notifier covers up the rightmost bar  

### ISSUE THREAD

**Issue by ghost** [Crylia/crylia-theme#38]
So my doubt is how to move it a little bit to the right

**Comment by Crylia** [comment]
What exactly do you mean, do you have a screenshot?

**Comment by ghost** [comment]
![2022-12-10_01-09](https://user-images.githubusercontent.com/87923259/206783983-3c4eed7d-7410-4f86-a952-2cdb9c7b26e4.png)

**Comment by ghost** [comment]
See that google chrome widget like covers up a bit of the bar 

I was asking that how to maybe shift the bar if possible

**Comment by ghost** [comment]
And I have one more issue 

How to override the normal wallpaper setup and use some wallpaper manager like variety

**Comment by Crylia** [comment]
> I was asking that how to maybe shift the bar if possible

Thats not really possible in an easy manner, but you can customize the widgets in the bar to remove some or add them to the left side

>How to override the normal wallpaper setup and use some wallpaper manager like variety

Remove the wallpaper from the config file

**Comment by ghost** [comment]
Ohk thanks
