### ISSUE TITLE
[QUESTION] How to change the font of workspaces from (1, 2, 3, ...) to a Japanese font (一 , 二, 三, 四, ...)

### ISSUE THREAD

**Issue by ghost** [Crylia/crylia-theme#39]
![2023-01-04_12-03](https://user-images.githubusercontent.com/87923259/210497326-c9ee2f81-b959-4f11-9e62-15138ebb95bf.png)

This font...

**Comment by Crylia** [comment]
https://github.com/Crylia/crylia-theme/blob/3f141601e1ce990dfc2df1480a2150b0dd6202bd/awesome/crylia_bar/init.lua#L15

You can edit the strings there to anything you like (Make sure your font supports kanji)

**Comment by ghost** [comment]
OK thanks

**Comment by ghost** [comment]
I edited the above file with the respective kanji fonts installed but its not showing up there in the status bar...
(I even rebooted after editing the file)
![pic1](https://user-images.githubusercontent.com/87923259/210546204-00764d3e-c7fe-4f61-ba3a-9942e02b7643.png)

**Comment by Crylia** [comment]
Ah sorry, you'd have to edit it here
https://github.com/Crylia/crylia-theme/blob/3f141601e1ce990dfc2df1480a2150b0dd6202bd/awesome/src/widgets/taglist.lua#L68
instead of object.index put the character depending on the index there(the index goes from 1 .. 9).

**Comment by ghost** [comment]
Would you mind elaborating how to put it in there, I mean I did this and now all workspaces just use "一"

![pic1](https://user-images.githubusercontent.com/87923259/210548236-27451778-6873-4644-a743-bcd32a9e002f.png)

**Comment by Crylia** [comment]
It works by iterating over all tags, you can use the object.index to check which you are on and then adjust the text.

e.g.

```lua
if object.index == 1 then
  tag_widget.container.margin.label:set_text("一")
elseif object.index == 2 then
  tag_widget.container.margin.label:set_text("二")
...
end
```

**Comment by ghost** [comment]
Yes it finally works, thank you very much.
