### ISSUE TITLE
[BUG] Dock stays on sometimes

### ISSUE THREAD

**Issue by bend-n** [Crylia/crylia-theme#40]
**Describe the bug**
The dock stays on when the cursor is out

**To Reproduce**
1. Open dock
2. <kbd>alt</kbd>+<kbd>tab</kbd> to a window
3. Move cursor around
4. Dock there until you put your cursor in and out of it.
5. Might have to try a few times

**Expected behavior**
Dock closes.

**Screenshots**
![image](https://user-images.githubusercontent.com/70787919/210664867-51f0da0a-3ea5-4ee4-8648-eef49e82d690.png)

**Information **
 - Archlinux
 - v4.3-1586-gee0663459

**Comment by Crylia** [comment]
Pretty weird in theory it should check when a client gets focused.
Could you try adding this -> `dock_intelligent_hide:again()` after this:
https://github.com/Crylia/crylia-theme/blob/3f141601e1ce990dfc2df1480a2150b0dd6202bd/awesome/crylia_bar/dock.lua#L290

(between the } and end)

```lua
  }
  dock_intelligent_hide:again()
end
```

**Comment by bend-n** [comment]
I cant seem to reproduce it with that patch.

**Comment by ghost** [comment]
I also experienced this very issue albeit I never used alt + tab, it just happened randomly when switching workspaces...

Yeah but after doing the above patch it is not happening.

**Comment by bend-n** [comment]
Yeah it just sometimes happens, but this makes it so that if anything is ever focused, it just turns off (i think), so, even when you get the bug, it will go away fast.

The little brown bar is still around usually tho

**Comment by Crylia** [comment]
I could add some more checks to various signals but since I've already rewritten the dock in the dev branch I think this little patch will be enough (Just comment on this issue if you think otherwise).

> The little brown bar is still around usually tho

Do you mean at the very bottom? Do you use a compositor?

**Comment by bend-n** [comment]
@Crylia No compositor, this brown bar 
![image](https://user-images.githubusercontent.com/70787919/210788591-eb9d5745-f324-4e80-89bc-bfd9fa548d5f.png)

**Comment by Crylia** [comment]
@bend-n This is basically the area that activates the dock (its an invisible widget) it shouldn't be visible even when not using a compositor since awesome supports pseudo transparency. However it sometimes can be visible, the easiest fix is to use a compositor (which has real transparency).

**Comment by bend-n** [comment]
@Crylia Still there when i use picom.

**Comment by Crylia** [comment]
@bend-n Uhhh, no idea then. You never changed the color of that thing right? And is your background in that color?

**Comment by bend-n** [comment]
Background is that color.
It also happens to the window toolbar things in floating windows, you just see wallpaper.
The floating windows are fixed with compositor though, not the brown bar.
