### ISSUE TITLE
Where can i edit the applications in the dock 

### ISSUE THREAD

**Issue by Eriasu08** [Crylia/crylia-theme#42]
Hey, i am to dump to change the appilcations in the dock i hope someone can show me in which file or even better which line in which file i find it and what i have to change

**Comment by Crylia** [comment]
https://github.com/Crylia/crylia-theme/blob/362c7478c8d90da923270b520c7045fb3e01c62f/awesome/src/theme/user_variables.lua#L83

In case someone stumbles across this question for a solution
