### ISSUE TITLE
[BUG] When i write `neofetch` on my fish config, i have a topbar like this

### ISSUE THREAD

**Issue by melatonia** [Crylia/crylia-theme#44]
When i first installed the theme i dont have window things (close, maximize, minimize). After i just add neofetch on my fish config, the window things come but my topbar looks like this:
![image](https://user-images.githubusercontent.com/110846681/227802454-36cea398-f7f1-4aa9-bc95-154d006137e1.png)

(This is what i mean by window things, sorry my english isnt very good.)
![image](https://user-images.githubusercontent.com/110846681/227802504-89a035cc-48be-4e3a-909d-439af26cd923.png)

Arch linux 

awesome v4.3-1588-gb54e50ad6 (Too long)
 • Compiled against Lua 5.4.4 (running with 0.9.2)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: /usr/share/lua/5.4/lgi/version.lua
 • Transparency enabled: yes
 • Custom search paths: no

**Comment by Crylia** [comment]
Uh, first of all that looks hilarious LOL. It looks like it is either the GPU widget, the temp widgets or the keyboard layout widget, can you remove those from your user_config.lua one by one to find out which one it is?

**Comment by melatonia** [comment]
It is keyboard layout widget. I dont have user_config.lua, do you mean user_veriables.lua?

**Comment by LastEmperor0** [comment]
When i remove from user_veriables.lua it just make default awesomewm config.

**Comment by LastEmperor0** [comment]
No its not compl

**Comment by melatonia** [comment]
@Crylia ?

**Comment by Crylia** [comment]
ah yes sorry, I changed some stuff in the devbranch (pretty much everything lol) so I forget how I did the stuff in the main branch ^^

**Comment by Crylia** [comment]
If its the keyboard layout widget, could you run this command and send me the result please?

`setxkbmap -query | grep layout | awk '{print $2}'`

**Comment by melatonia** [comment]
US @Crylia

**Comment by Crylia** [comment]
Are you sure it's the keyboard layout widget then? Because it should only ne US in that case

**Comment by melatonia** [comment]
If i click it, shows the layouts

**Comment by Crylia** [comment]
Try to remove the widget from the user_variables.lua and see if its still there, if yes remove other widgets until its gone then report back which one it was

**Comment by melatonia** [comment]
When i add -- to kblayout (--kblayout = { "de", "ru" },) it comes back to default awesomewm.

**Comment by Crylia** [comment]
Ah sorry, you need to comment out this line here https://github.com/Crylia/crylia-theme/blob/96a0d33b25b4da4348b24eec462b077b7af3022b/awesome/crylia_bar/init.lua#L36
I thought I had the widget declaration already moved in there, sorry

**Comment by melatonia** [comment]
No problem i am trying now

**Comment by melatonia** [comment]
Yes it removed but now i dont have any minimize maximize etc.
![image](https://user-images.githubusercontent.com/110846681/228031994-574c3b5d-ac97-4b43-8ee6-6c287cc6cb91.png)

**Comment by Crylia** [comment]
This is really weird, do they appear when you press super+g twice? (toggle floating off and on) or try super+m twice to toggle maximise

**Comment by melatonia** [comment]
When i press super+g it appears TYSM

**Comment by melatonia** [comment]
I am so sorry but how can i resize the windows?

**Comment by Crylia** [comment]
either rightclick on the titlebar and it should automatically start, or use super+rmb anywhere on the window
