### ISSUE TITLE
[is a Fix] is not a Issue

### ISSUE THREAD

**Issue by ghost** [Crylia/crylia-theme#49]
i fix the Battery Bug

u need to edit the init file in .config/awesome/crylia_bar/init.lua

and s.battery to require()
Like this (My Panel):
require("crylia_bar.right_bar")(s, { s.battery, s.bluetooth, s.network, s.cpu_usage, s.ram_info, s.clock, s.powerbutton })

i hope i can help you :D
 
EDIT:
Remove the -- here ->
--s.battery = require("src.widgets.battery")

**Comment by Crylia** [comment]
Please don't open a separate issue for a fix of the original one. #48
