### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by peat734** [Crylia/crylia-theme#5]
**Describe the bug**
all icons are not working

**To Reproduce**
just on the desktop

**Expected behavior**
I expected the icons to be visable

**Screenshots**

**Information (please complete the following information):**
 - EndeavorOS
 - Awesome Version 
 - Error

**Additional context**

**Comment by Crylia** [comment]
Have you changed the icon them in user_vars.lua? If yes then it probably doesnt work with my icon_helper.lua since its pretty poorly written and only really works with Papirus.

**Comment by peat734** [comment]
yeah it doesn't work. Unlucky. Nice rice tho

**Comment by Crylia** [comment]
Thanks, I'm gonna close this now please reopen if there is more to that

**Comment by Shorakie** [comment]
i had to install the `papirus-icon-theme` package, in order for the icons to show on my arch setup.
