### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by anhuar-ma** [Crylia/crylia-theme#50]
How can I eliminate the gaps between the center, left and right bar and the current window? 

I alredy set Theme.useless_gap = dpi(0), but I want no gap between the bar and the window

**Comment by Crylia** [comment]
https://github.com/Crylia/crylia-theme/blob/324866e7654496799bfea021512485881db72c78/awesome/crylia_bar/right_bar.lua#L25-L27
Set the top struts to I think 50 in all bar configs, here the link for the right one (need to change the center too)

https://github.com/Crylia/crylia-theme/blob/324866e7654496799bfea021512485881db72c78/awesome/crylia_bar/right_bar.lua#L19-L20
Set those margins to 0 for all bars again if you wish to have the bars right at the edge of the screen

EDIT: You might need to play with the top_struts value when you remove the margins too.

**Comment by anhuar-ma** [comment]
Thank you very much, it worked
