### ISSUE TITLE
[QUESTION] Eliminate awesome titlebar

### ISSUE THREAD

**Issue by anhuar-ma** [Crylia/crylia-theme#51]
![2023-10-16_19-45](https://github.com/Crylia/crylia-theme/assets/135924649/5b898fad-8153-4987-a062-f22570800f54)

How can I eliminate the titlebar on brave, I tried editing rules.lua en setting titlebras_enabled to false but it didn't work.

**Comment by Crylia** [comment]
I think its a bug where the client has a maximized state from a previous DE session, try toggling floating and maximizing a little and it should go away in tiling mode

**Comment by anhuar-ma** [comment]
Yes, like you said it was something with the floating and maximize , I solved it by editing rules.lua and the way floating worked on client_key.lua
