### ISSUE TITLE
[QUESTION]Hide / show wibox

### ISSUE THREAD

**Issue by anhuar-ma** [Crylia/crylia-theme#52]
Sorry to bother again , I want to hide the crylia_bar(the 3 top bars) with a shortcut, I tried what the arch wiki said:

`awful.key({ modkey }, "b",
          function ()
              myscreen = awful.screen.focused()
              myscreen.mywibox.visible = not myscreen.mywibox.visible
          end,
          {description = "toggle statusbar"}
),
`
but I got the error: 

`attempt to index a nil value (field 'mywibox')`

**Comment by Crylia** [comment]
You will have to make a shortcut that sends a signal to all 3 bars and toggles them

**Comment by anhuar-ma** [comment]
How could I do that?

**Comment by anhuar-ma** [comment]
Could you also tell me how can I edit the size of the bar, for example I don't now yet if I should edit the widgets or the bar config to make it smaller.
