### ISSUE TITLE
[QUESTION] Unsure how to change the affects of from a keybinding

### ISSUE THREAD

**Issue by chookity-pokk** [Crylia/crylia-theme#53]
The title isn't super great but I am not entirely sure how to sum the problem up. Basically when I hit the Windows key and Backspace my mouse turns into a plus icon and I can't get it go away without clicking on a window. When I click on a window though it goes into this bordered mode and I can't get it out of that. I am also having a hard time finding out what this is called because I can't find what the keybinding is actually doing. Any help would be greatly appreciated.
![image](https://github.com/Crylia/crylia-theme/assets/24358100/06c0e372-2532-457b-a726-8fe56545a09e)

**Comment by chookity-pokk** [comment]
I swear I looked into this before posting and within a minute after posting I found my solution. It's just `C-g`.

**Comment by Crylia** [comment]
Lol that always happens.
Btw that keybinding is for marking windows as floating

**Comment by chookity-pokk** [comment]
Thanks for the help haha!
