### ISSUE TITLE
[QUESTION] Lacking alacritty terminal config

### ISSUE THREAD

**Issue by memorelic** [Crylia/crylia-theme#56]
Hey, Your theme is really nice, but when I try to use it following README file, I found that alacritty config file is missing. it looks like you have change your terminal to kitty? could you please put alacritty config on this repo again? I really like your original config.

**Comment by Crylia** [comment]
You can simply checkout to an older commit for that conf. But tbh I simply lack the time to currently work on the theme otherwise I would've updated it in a better way.

Maybe in the future

**Comment by memorelic** [comment]
Oh, I didn't notice that there is another branch. Thank you for your kind response. Have a nice day!
