### ISSUE TITLE
[QUESTION] Could you please tell me about your lightdm and light-locker config?

### ISSUE THREAD

**Issue by memorelic** [Crylia/crylia-theme#58]
Hello, I'm a little bit confused with the lightdm and light-locker config. 
According to Arch wiki, I need to install a greeter then I can start lightdm. Which greeter do you use and where can I find the theme? I have searched your repo for many times, but I didn't find one.
Forgive me, it seems it's not easy to run this theme fully correct since time past so long, there're so many changes, I could only ask you for some help.

**Comment by Crylia** [comment]
Should be called `lightdm-webkit2-greeter` in  the AUR

**Comment by memorelic** [comment]
Thanks, Is there any other config I need to do with the greeter? I have read the wiki of lightdm-webkit2-greeter, it says I need to customize it by some 'theme', but I didn't find one at this repo. Did I miss something?

**Comment by Crylia** [comment]
I never included any greeter theme in my rice

**Comment by memorelic** [comment]
Ok, thank you, I guess I must figure out which point did I miss.
