### ISSUE TITLE
[QUESTION] Do you plan to rewrite the volume controller using pulseaudio_dbus?

### ISSUE THREAD

**Issue by CloudyChris** [Crylia/crylia-theme#59]

**Comment by Crylia** [comment]
I'm currently not using/developing awesome anymore, so no. But I did rewrite it in my dev branch, but I can't remember if its done. If anyone wants to merge it specifically I'm open to accept PR's.

**Comment by Crylia** [comment]
Forgot to mention. The dbus implementation from pulse has its problems, I spend a good ammount of time trying to use it but no luck, even all those solutions out there didn't work for me. Same problem with the lua c binding libs, never worked for me. At one point I started developing my own but the lua clib was too annoying to use so I ditched it and the current solution I have in my devbranch was "good enough" for me.

**Comment by CloudyChris** [comment]
I understand. To be honest, I'm rather frustrated with the single threaded nature of this as well... I mean, if I want a decent experience I'd need to make my own complementary software like a launcher and desktop entry finder separate from Awesome because trying to look up desktop entries just reduces performance to ash, and it's a bit complicated to do it async (I was lazy).
Thanks for all the good ideas and your hard work! I'll keep using this for a while until I'll muster up the courage to try hyprland...
