### ISSUE TITLE
[BUG] /home/user/.config/awesome/crylia_bar/init.lua:26: module 'src.modules.volume_controller' not found

### ISSUE THREAD

**Issue by IruzzArcana** [Crylia/crylia-theme#8]
**Describe the bug**
As shown in the screenshot below, by the look of it looks like a missing file.

**To Reproduce**
1. Fresh clone and install of the theme.

**Screenshots**
![2022-05-14_11-51](https://user-images.githubusercontent.com/89710975/168423034-b4d8d71f-9d9b-41a5-9cf4-301935f81948.png)

**Information (please complete the following information):**
 - Arch Linux
 - awesome v4.3-1360-gc539e0e43

**Comment by Crylia** [comment]
Thanks, this was something supposed to be removed
