### ISSUE TITLE
[BUG] Probably missing some setting or dependency

### ISSUE THREAD

**Issue by Vantazz** [Crylia/crylia-theme#9]
**Describe the bug**
I cannot get Alacritty to actually use the font or rice that is set in the config file.
I can also not get the mod+w rofi bind to work 

![image](https://user-images.githubusercontent.com/31926730/168655561-32b29f16-c49b-4332-8330-7d5a2714d4dd.png)
![image](https://user-images.githubusercontent.com/31926730/168655761-f89a6479-a76e-4446-b6b8-574de7af3031.png)

**To Reproduce**
Used Archinstall to get a fresh awesomewm install, switched to zsh. 
installed dependencies including nerd-fonts-complete.
copied dotfiles.

**Information (please complete the following information):**
 - Arch
 - awesome v4.3-1360-gc539e0e43 (Too long)
 • Compiled against Lua 5.4.4 (running with 0.9.2)

**Comment by Crylia** [comment]
The mod+w bind is actually a awesome menu that I removed because it lacks too many features. I forgot to remove that binding

The font issue is weird, it looks like you are using the right one tho. I downloaded the font files from here https://github.com/romkatv/powerlevel10k#meslo-nerd-font-patched-for-powerlevel10k, maybe you got the wrong files?

**Comment by Shorakie** [comment]
i also had the same issue with the alacrity, i switched to `kitty` and the problem was gone.

**Comment by Crylia** [comment]
@Shorakie Did you install the MesloLGS NF Font?

**Comment by Vantazz** [comment]
Figured out the font issue at least, on my system they were called MesloLGS Nerd Font and not MesloLGS NF.
I've yet to find the config file for the lock screen so I cannot fix the same issue there. 

Other than that I only have one issue and it's that I cannot get your alacritty rice to work by that I mean the bar above the terminal input whether it is some super strange PS1 or not I have no clue.

**Comment by Shorakie** [comment]
> @Shorakie Did you install the MesloLGS NF Font?

No but i changed the Alacrity config to use another font in my case Fira Code.
however today i tested alacrity again and it was rendering with correct letter width.

**Comment by Shorakie** [comment]
> Other than that I only have one issue and it's that I cannot get your alacritty rice to work by that I mean the bar above the terminal input whether it is some super strange PS1 or not I have no clue.

if i have guessed correctly the owner is using oh-my-zsh with the power10k theme

**Comment by Vantazz** [comment]
![image](https://user-images.githubusercontent.com/31926730/168845850-e2b11857-4c60-415e-a18e-a45eb8385498.png)
True enough, thanks :)

One last question, if you are not using mod+w to launch programs without using a terminal then what are you using?

**Comment by Crylia** [comment]
@Tickle mod+d launches rofi, other than that there is always the dock.

**Comment by Vantazz** [comment]
Ah yeah that is what I assumed, I am running into an issue with that bind "The following errors were detected when starting rofi: failed to resolve variable 'border' in: 'window { border-color: var(border);}'" covers the entire screen in white with that error in the top left

**Comment by Crylia** [comment]
@Tickle I think it would be best to open a new issue for that, but please make sure you are using rofi git and not the old version they package
